   name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get
          cd ios && pod repo update && cd ..

      - name: Build IOS App
        run: flutter build ipa --release --no-codesign

      - name: Crear estructura IPA final
        run: |
          mkdir -p build/ios/iphoneos/Payload
          # Este comando busca de forma inteligente cualquier carpeta .app dentro de build/ios/ y la mueve a Payload
          find build/ios/ -name "*.app" -type d -exec mv {} build/ios/iphoneos/Payload/ \;
          cd build/ios/iphoneos
          zip -r mi_aplicacion.ipa Payload

      - name: Subir el archivo IPA como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-release-ipa
          path: build/ios/iphoneos/mi_aplicacion.ipa
